### ISSUE TITLE
EPERM: operation not permitted

### ISSUE THREAD

**Issue by boardtc** [m4heshd/whatsapp-desktop-dark#120]
From WADark-0.3.4941-Windows.zip running WADark.exe (Node.js 12.9.1) gives output:

Theme "Default" was successfully applied.

Backing up..
Extracting..
Injecting styles..
Replacing files..
Error: EPERM: operation not permitted, stat 'C:\Program Files\WindowsApps'
    at Object.statSync (fs.js:898:3)
    at Object.statSync (C:\Users\user1\Downloads\WADark-Windows\WADark.exe:217:47)
    at Object.statSync (C:\Users\user1\Downloads\WADark-Windows\node_modules\graceful-fs\polyfills.js:307:34)
    at checkParentPathsSync (C:\Users\user1\Downloads\WADark-Windows\node_modules\fs-extra\lib\util\stat.js:140:21)
    at checkParentPathsSync (C:\Users\user1\Downloads\WADark-Windows\node_modules\fs-extra\lib\util\stat.js:151:10)
    at checkParentPathsSync (C:\Users\user1\Downloads\WADark-Windows\node_modules\fs-extra\lib\util\stat.js:151:10)
    at Object.checkParentPathsSync (C:\Users\user1\Downloads\WADark-Windows\node_modules\fs-extra\lib\util\stat.js:151:10)
    at Object.copySync (C:\Users\user1\Downloads\WADark-Windows\node_modules\fs-extra\lib\copy-sync\copy-sync.js:25:8)
    at C:\Users\user1\Downloads\WADark-Windows\run-win32.js:109:28
    at C:\Users\user1\Downloads\WADark-Windows\node_modules\asar\lib\asar.js:162:18 {
  errno: -4048,
  syscall: 'stat',
  code: 'EPERM',
  path: 'C:\\Program Files\\WindowsApps'
}

Right-clicking and running with admin rights and it just flashes, it does not open a window.

**Comment by m4heshd** [comment]
This is because you installed WA Desktop from the store. WADark is not compatible with that version which is written in the documentation with big red lettering. Closing the issue.

**Comment by boardtc** [comment]
@m4heshd interesting! I can't find a home for WhatsApp Desktop, where should I download it from?

**Comment by boardtc** [comment]
Ok. I got my finger out, clicked on 64-bit link from https://www.whatsapp.com/download/ & installed & opened. Then I reinstalled this (with WhatsApp Desktop open), I selected WhastApp Dark and styles were injected it said!
But then I got the error: EPERM: operation not permitted, stat 'C:\Program Files\WindowsApps'
I opened WhatsApp Desktop and it's still the normal style.

I can change the chat wallpaper to black but surely the dark theme is more than that?

**Comment by boardtc** [comment]
I think this error needs to be reopened **please**

**Comment by m4heshd** [comment]
Did you uninstall the store version before you reinstalled the direct downloaded version?

**Comment by boardtc** [comment]
Thanks for your patience. I did a full uninstall and reinstall and I'm in business!

**Comment by m4heshd** [comment]
Great to hear. Enjoy..
