### ISSUE TITLE
New GUI issues when re-installing WADark with a different theme

### ISSUE THREAD

**Issue by Idomo** [m4heshd/whatsapp-desktop-dark#122]
WADark v0.4.315 - Just tried to re-run the installation with a different theme and got this error:
```
Uncaught Exception:
Error: Unable to find a valid app
    at Object.<anonymous> (/Applications/WhatsApp.app/Contents/Resources/electron.asar/browser/init.js:120:9)
    at Object.<anonymous> (/Applications/WhatsApp.app/Contents/Resources/electron.asar/browser/init.js:190:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:746:12)
    at startup (internal/bootstrap/node.js:282:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:759:3)
```

* Edit - One of this solved the issue: Re-installing WhatsApp or deleting the `backup` folder

**Comment by m4heshd** [comment]
Hi @Idomo,
I can confirm this and It'll be worked on in the next release.

**Comment by m4heshd** [comment]
Unfortunately this issue had to be pushed for the next release because debugging it is a bit time consuming at the moment. Sorry about that.
