### ISSUE TITLE
WADark for Mac does not work on Whatsapp version 0.4.1299

### ISSUE THREAD

**Issue by rarmellini** [m4heshd/whatsapp-desktop-dark#166]
After running the script, it keeps asking me to update whatsapp desktop, although I am already on the latest version.

**Comment by SantiagoITHS** [comment]
Have the same issue, tried installing it with the web GUI v0.4.930 but it didn't work. 

Macbook Pro 13" 2019
Catalina 10.15.3

**Comment by marioleal** [comment]
Are you guys getting this error on console: Error: EACCES: permission denied, unlink ... ?

Try running with sudo, worked for me.

**Comment by rarmellini** [comment]
> Are you guys getting this error on console: Error: EACCES: permission denied, unlink ... ?
> 
> Try running with sudo, worked for me.

Didn't get any error. Script ran smoothly. However, when I kick off whatsapp desktop, it throws a message saying that I need to update and never goes beyond that point. What version of whatsapp are you running?

**Comment by SantiagoITHS** [comment]
just ran with sudo, worked perfectly

**Comment by marioleal** [comment]
@rarmellini 

0.4.930

Seems like you aren't on the latest.

Are you sure you are not using the appstore whatsapp?

**Comment by SantiagoITHS** [comment]
Damn, accidentally upgraded to version 4.1300, the script now doesnt work at all. 

~~~~ WhatsApp Desktop Dark Mode by m4heshd ~~~~


events.js:186
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3210
    at Server.setupListenHandle [as _listen2] (net.js:1228:14)
    at listenInCluster (net.js:1276:12)
    at Server.listen (net.js:1364:7)
    at Function.listen (/Users/shernandez/Downloads/WADark-macOS/node_modules/express/lib/application.js:618:24)
    at Object.exports.startGUI (/Users/shernandez/Downloads/WADark-macOS/run-gui.js:35:22)
    at Object.<anonymous> (/Users/shernandez/Downloads/WADark-macOS/index.js:24:34)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1255:8)
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 3210

**Comment by rcerro** [comment]
It's working for me as you can see below:

![image](https://user-images.githubusercontent.com/42202052/76307573-fe6caf80-62c0-11ea-83e0-6d909815c69a.png)

just change permissions (a+x) and execute as root.

**Comment by m4heshd** [comment]
> Damn, accidentally upgraded to version 4.1300, the script now doesnt work at all.

Hi @SantiagoITHS, 
This error has occurred because another instance of the installer is running in the background. Please close them before you start a new install. It's not related to your WA build at all.

**Comment by m4heshd** [comment]
@rarmellini You seems to be on an older version of WhatsApp desktop. Please try reinstalling the latest version. No one else is reporting this issue.

**Comment by gferreroferri** [comment]
I get this error with the latest version of WhatsApp app on Mac 0.4.1302
Error: EACCES: permission denied, unlink '/Applications/WhatsApp.app/Contents/Resources/app.asar'
    at Object.unlinkSync (fs.js:1018:3)
    at mayCopyFile (/Users/guillermo/Desktop/WADark-macOS/node_modules/fs-extra/lib/copy-sync/copy-sync.js:59:8)
    at onFile (/Users/guillermo/Desktop/WADark-macOS/node_modules/fs-extra/lib/copy-sync/copy-sync.js:54:10)
    at getStats (/Users/guillermo/Desktop/WADark-macOS/node_modules/fs-extra/lib/copy-sync/copy-sync.js:48:44)
    at startCopy (/Users/guillermo/Desktop/WADark-macOS/node_modules/fs-extra/lib/copy-sync/copy-sync.js:38:10)
    at handleFilterAndCopy (/Users/guillermo/Desktop/WADark-macOS/node_modules/fs-extra/lib/copy-sync/copy-sync.js:33:10)
    at Object.copySync (/Users/guillermo/Desktop/WADark-macOS/node_modules/fs-extra/lib/copy-sync/copy-sync.js:26:10)
    at /Users/guillermo/Desktop/WADark-macOS/run-gui.js:227:28
    at /Users/guillermo/Desktop/WADark-macOS/node_modules/asar/lib/asar.js:162:18
    at writeFileListToStream (/Users/guillermo/Desktop/WADark-macOS/node_modules/asar/lib/disk.js:42:10) {
  errno: -13,
  syscall: 'unlink',
  code: 'EACCES',
  path: '/Applications/WhatsApp.app/Contents/Resources/app.asar'
}

**Comment by haveneersrobin** [comment]
@gferreroferri Just tested on WhatsApp 1302, works perfectly. Just run the WADark script with sudo.

**Comment by jhult** [comment]
Works for me on version 1307.
