### ISSUE TITLE
WA Dark mode does not work with Version 0.4.1302

### ISSUE THREAD

**Issue by gferreroferri** [m4heshd/whatsapp-desktop-dark#169]
Hi,
WA Dark mode does not work with Version 0.4.1302 macOS version. I get the following error:

Error: EACCES: permission denied, unlink '/Applications/WhatsApp.app/Contents/Resources/app.asar'
at Object.unlinkSync (fs.js:1018:3)
at mayCopyFile (/Users/guillermo/Desktop/WADark-macOS/node_modules/fs-extra/lib/copy-sync/copy-sync.js:59:8)
at onFile (/Users/guillermo/Desktop/WADark-macOS/node_modules/fs-extra/lib/copy-sync/copy-sync.js:54:10)
at getStats (/Users/guillermo/Desktop/WADark-macOS/node_modules/fs-extra/lib/copy-sync/copy-sync.js:48:44)
at startCopy (/Users/guillermo/Desktop/WADark-macOS/node_modules/fs-extra/lib/copy-sync/copy-sync.js:38:10)
at handleFilterAndCopy (/Users/guillermo/Desktop/WADark-macOS/node_modules/fs-extra/lib/copy-sync/copy-sync.js:33:10)
at Object.copySync (/Users/guillermo/Desktop/WADark-macOS/node_modules/fs-extra/lib/copy-sync/copy-sync.js:26:10)
at /Users/guillermo/Desktop/WADark-macOS/run-gui.js:227:28
at /Users/guillermo/Desktop/WADark-macOS/node_modules/asar/lib/asar.js:162:18
at writeFileListToStream (/Users/guillermo/Desktop/WADark-macOS/node_modules/asar/lib/disk.js:42:10) {
errno: -13,
syscall: 'unlink',
code: 'EACCES',
path: '/Applications/WhatsApp.app/Contents/Resources/app.asar'
}

**Comment by m4heshd** [comment]
Did you install WhatsApp via the store?

**Comment by gferreroferri** [comment]
Yes

El 19 mar 2020, a las 13:44, Mahesh Bandara Wijerathna <notifications@github.com> escribió:

﻿

Did you install WhatsApp via the store?
