### ISSUE TITLE
[ALTERNATIVE FORK] Stopped working on version 0.4.2080 for Windows / 0.4.2081 for macOS

### ISSUE THREAD

**Issue by Felluz** [m4heshd/whatsapp-desktop-dark#172]
I opened the app this morning and saw that it was back to the default theme, then I unzipped the files to apply the dark theme, after completing that was the result. I've tried all themes but none work, it stays the same.
![8v6hu2ojrQ](https://user-images.githubusercontent.com/16976344/77667497-0a16d200-6f61-11ea-8ce4-32e5c27a12d3.png)

**Comment by UnderEu** [comment]
Are you able to switch themes on-the-fly w/ the switcher button, next to your profile photo?

**Comment by Felluz** [comment]
> Are you able to switch themes on-the-fly w/ the switcher button, next to your profile photo?

no, the button disappeared as you can see in the screenshot.

**Comment by BerkayDrsn** [comment]
Also broken for me since this morning, presumably due to latest WhatsApp update. (macOS Catalina)

**Comment by iambudi** [comment]
Broken in Catalina as well.

**Comment by SixSiege** [comment]
Same here (version 0.4.2081)

**Comment by Reycho** [comment]
Same here (Windows 10) But mines worse.

**Comment by UnderEu** [comment]
**WORKAROUND**: The following attachment enables the official dark theme as a temporary replacement. Replace the index.html files on the following path with the provided one:

[0.4.2080-Workaround.zip](https://github.com/m4heshd/whatsapp-desktop-dark/files/4394259/0.4.2080-Workaround.zip)
**Windows**: WADark-Windows > styles > win32 
**macOS**: WADark-macOS > styles > darwin 

Apply using the "default" theme on the GUI installer.

**Comment by mubashir-rehman** [comment]
> I opened the app this morning and saw that it was back to the default theme, then I unzipped the files to apply the dark theme, after completing that was the result. I've tried all themes but none work, it stays the same.
> ![8v6hu2ojrQ](https://user-images.githubusercontent.com/16976344/77667497-0a16d200-6f61-11ea-8ce4-32e5c27a12d3.png)

btw how did you blurred those parts??

**Comment by UnderEu** [comment]
> > I opened the app this morning and saw that it was back to the default theme, then I unzipped the files to apply the dark theme, after completing that was the result. I've tried all themes but none work, it stays the same.
> > ![8v6hu2ojrQ](https://user-images.githubusercontent.com/16976344/77667497-0a16d200-6f61-11ea-8ce4-32e5c27a12d3.png)
> 
> btw how did you blurred those parts??

By using any image editor such as Adobe Photoshop, GIMP, Pixelmator etc.

**Comment by Alessandro3840** [comment]
I confirm it stopped working also on macOS

**Comment by sorino8** [comment]
> 
> 
> **WORKAROUND**: The following attachment enables the official dark theme as a temporary replacement. Replace the index.html files on the following path with the provided one:
> 
> [0.4.2080-Workaround.zip](https://github.com/m4heshd/whatsapp-desktop-dark/files/4394259/0.4.2080-Workaround.zip)
> **Windows**: WADark-Windows > styles > win32
> **macOS**: WADark-macOS > styles > darwin
> 
> Apply using the "default" theme on the GUI installer.

worked for me. thanks man. nice workaround until author releases new version.

**Comment by Joelius300** [comment]
Can confirm that it stopped working on Windows 10. Reinstalling (both whatsapp and the dark theme) didn't help.

Can also confirm that the workaround by @UnderEu works.

**Comment by syntaxer** [comment]
> 
> 
> **WORKAROUND**: The following attachment enables the official dark theme as a temporary replacement. Replace the index.html files on the following path with the provided one:
> 
> [0.4.2080-Workaround.zip](https://github.com/m4heshd/whatsapp-desktop-dark/files/4394259/0.4.2080-Workaround.zip)
> **Windows**: WADark-Windows > styles > win32
> **macOS**: WADark-macOS > styles > darwin
> 
> Apply using the "default" theme on the GUI installer.

Worked, thanks

**Comment by ghost** [comment]
Pls help. Applied this fix, set to default, changed to deep black; whatsapp not starting anymore. Does this fix only apply for the default? And how do I get my Whatsapp back for now?

EDIT: Just launched the WhatsAppSetup.exe again. Fixed it, also WAdark default working properly. Just not so sure if I should try anything but the default right now.

**Comment by Ga1aga** [comment]
> 
> 
> **WORKAROUND**: The following attachment enables the official dark theme as a temporary replacement. Replace the index.html files on the following path with the provided one:
> 
> [0.4.2080-Workaround.zip](https://github.com/m4heshd/whatsapp-desktop-dark/files/4394259/0.4.2080-Workaround.zip)
> **Windows**: WADark-Windows > styles > win32
> **macOS**: WADark-macOS > styles > darwin
> 
> Apply using the "default" theme on the GUI installer.

**Comment by Ga1aga** [comment]
> 
> 
> > > I opened the app this morning and saw that it was back to the default theme, then I unzipped the files to apply the dark theme, after completing that was the result. I've tried all themes but none work, it stays the same.
> > > ![8v6hu2ojrQ](https://user-images.githubusercontent.com/16976344/77667497-0a16d200-6f61-11ea-8ce4-32e5c27a12d3.png)
> > 
> > 
> > btw how did you blurred those parts??
> 
> By using any image editor such as Adobe Photoshop, GIMP, Pixelmator etc.

Can confirm the Workaround works, thank you!

**Comment by Ga1aga** [comment]
> 
> 
> **WORKAROUND**: The following attachment enables the official dark theme as a temporary replacement. Replace the index.html files on the following path with the provided one:
> 
> [0.4.2080-Workaround.zip](https://github.com/m4heshd/whatsapp-desktop-dark/files/4394259/0.4.2080-Workaround.zip)
> **Windows**: WADark-Windows > styles > win32
> **macOS**: WADark-macOS > styles > darwin
> 
> Apply using the "default" theme on the GUI installer.

Can confirm the Workaround works, thank you!

**Comment by devmisa** [comment]
> **WORKAROUND**: The following attachment enables the official dark theme as a temporary replacement. Replace the index.html files on the following path with the provided one:
> 
> [0.4.2080-Workaround.zip](https://github.com/m4heshd/whatsapp-desktop-dark/files/4394259/0.4.2080-Workaround.zip)
> **Windows**: WADark-Windows > styles > win32
> **macOS**: WADark-macOS > styles > darwin
> 
> Apply using the "default" theme on the GUI installer.

Worked, thx !

**Comment by gabrielclow** [comment]
The workaround provided by @UnderEu did not work correctly here for some reason, but what I did for now was go into %localappdata%\WhatsApp\app-0.4.1307 and ran the older version I had already installed WADark from there.

**Comment by UnderEu** [comment]
> Pls help. Applied this fix, set to default, changed to deep black; whatsapp not starting anymore. Does this fix only apply for the default? And how do I get my Whatsapp back for now?
> 
> EDIT: Just launched the WhatsAppSetup.exe again. Fixed it, also WAdark default working properly. Just not so sure if I should try anything but the default right now.

Only the official dark theme (default) is working, every other there is broken. We have to stick with that, for now.

> The workaround provided by @UnderEu did not work correctly here for some reason, but what I did for now was go into %localappdata%\WhatsApp\app-0.4.1307 and ran the older version I had already installed WADark from there.

Eventually, your instance will self update and breaks over and over again. So... your mileage will vary.

**Comment by SixSiege** [comment]
> **WORKAROUND**: The following attachment enables the official dark theme as a temporary replacement. Replace the index.html files on the following path with the provided one:
> 
> [0.4.2080-Workaround.zip](https://github.com/m4heshd/whatsapp-desktop-dark/files/4394259/0.4.2080-Workaround.zip)
> **Windows**: WADark-Windows > styles > win32
> **macOS**: WADark-macOS > styles > darwin
> 
> Apply using the "default" theme on the GUI installer.

Worked, Thanks for the workaround!

**Comment by holymode** [comment]
Another work around is deleting the newest update. 
Go to C:\Users\xxx\AppData\Local\WhatsApp and delete the most recent app-0.4.xxxx, old version should still be there.

**Comment by shafwan7** [comment]
> 
> 
> **WORKAROUND**: The following attachment enables the official dark theme as a temporary replacement. Replace the index.html files on the following path with the provided one:
> 
> [0.4.2080-Workaround.zip](https://github.com/m4heshd/whatsapp-desktop-dark/files/4394259/0.4.2080-Workaround.zip)
> **Windows**: WADark-Windows > styles > win32
> **macOS**: WADark-macOS > styles > darwin
> 
> Apply using the "default" theme on the GUI installer.

Work for Win10 v1909.
and still waiting for Dev to update all those things.

**Comment by nayefc** [comment]
Many people are watching this issue for a real fix (or for real issues with this workaround). There is no need to post yet another "works!" comment. We all know it works by now.

**Comment by TOAOQ** [comment]
Needed to apply this workaround on a clean install to get it working.

**Comment by ekiscrim** [comment]
Yep, applied on a clean install this workaround works.

**Comment by Troper211** [comment]
it works, thanks

**Comment by mechanizzed** [comment]
Works!

Please, update readme with this fix.

**Comment by iambudi** [comment]
> **WORKAROUND**: The following attachment enables the official dark theme as a temporary replacement. Replace the index.html files on the following path with the provided one:
> 
> [0.4.2080-Workaround.zip](https://github.com/m4heshd/whatsapp-desktop-dark/files/4394259/0.4.2080-Workaround.zip)
> **Windows**: WADark-Windows > styles > win32
> **macOS**: WADark-macOS > styles > darwin
> 
> Apply using the "default" theme on the GUI installer.

I can't get it work on catalina, partial color change only. Whatsapp Version 0.4.2081.

**Comment by UnderEu** [comment]
> Works!
> 
> Please, update readme with this fix.

It isn't a fix, it's a workaround. The proper fix who covers every provided theme will be pushed whenever it's fixed.

**Comment by ozzysp** [comment]
Thank to this workaround, the Dark Theme is back again!!! Thank you, friends!

**Comment by UnderEu** [comment]
It looks like, even with this workaround, some elements are broken: Emoji picker and message quotes, i.e..
Also, we're aware there's a new client update being pushed (0.4.2088) and the same issues remain. The dev team is working on those and they'll release the proper fixes whenever possible. Please, be patient.

**Comment by AhmadChaiban** [comment]
> **WORKAROUND**: The following attachment enables the official dark theme as a temporary replacement. Replace the index.html files on the following path with the provided one:
> 
> [0.4.2080-Workaround.zip](https://github.com/m4heshd/whatsapp-desktop-dark/files/4394259/0.4.2080-Workaround.zip)
> **Windows**: WADark-Windows > styles > win32
> **macOS**: WADark-macOS > styles > darwin
> 
> Apply using the "default" theme on the GUI installer.

Can Confirm, Worked for me as well. Thank you <3

**Comment by ronny332** [comment]
The workaround works partially on my macOS installation (WA version 0.4.2088). The button for theme switching isn't reachable. A click on it results in navigating to the status updates. But, at least, it works very well and everything is in beautiful black again ;).

**Comment by eliveltonsales** [comment]
> **WORKAROUND**: The following attachment enables the official dark theme as a temporary replacement. Replace the index.html files on the following path with the provided one:
> 
> [0.4.2080-Workaround.zip](https://github.com/m4heshd/whatsapp-desktop-dark/files/4394259/0.4.2080-Workaround.zip)
> **Windows**: WADark-Windows > styles > win32
> **macOS**: WADark-macOS > styles > darwin
> 
> Apply using the "default" theme on the GUI installer.

Tested, working at v0.4.2088 W10

**Comment by sudhxnva** [comment]
> **WORKAROUND**: The following attachment enables the official dark theme as a temporary replacement. Replace the index.html files on the following path with the provided one:
> 
> [0.4.2080-Workaround.zip](https://github.com/m4heshd/whatsapp-desktop-dark/files/4394259/0.4.2080-Workaround.zip)
> **Windows**: WADark-Windows > styles > win32
> **macOS**: WADark-macOS > styles > darwin
> 
> Apply using the "default" theme on the GUI installer.

Works! Thanks!

**Comment by alexandrerochasalles** [comment]
> **WORKAROUND**: The following attachment enables the official dark theme as a temporary replacement. Replace the index.html files on the following path with the provided one:
> 
> [0.4.2080-Workaround.zip](https://github.com/m4heshd/whatsapp-desktop-dark/files/4394259/0.4.2080-Workaround.zip)
> **Windows**: WADark-Windows > styles > win32
> **macOS**: WADark-macOS > styles > darwin
> 
> Apply using the "default" theme on the GUI installer.

Still working on macOS 0.4.2088 version!!

**Comment by marco-prolo** [comment]
> **WORKAROUND**: The following attachment enables the official dark theme as a temporary replacement. Replace the index.html files on the following path with the provided one:
> 
> [0.4.2080-Workaround.zip](https://github.com/m4heshd/whatsapp-desktop-dark/files/4394259/0.4.2080-Workaround.zip)
> **Windows**: WADark-Windows > styles > win32
> **macOS**: WADark-macOS > styles > darwin
> 
> Apply using the "default" theme on the GUI installer.


Works on Catalina! Sadly the button to switch between light and dark mode isn't there anymore. Am I missing something or does the fix not fix that in particular?

**Comment by feliperaimo** [comment]
> **WORKAROUND**: The following attachment enables the official dark theme as a temporary replacement. Replace the index.html files on the following path with the provided one:
> 
> [0.4.2080-Workaround.zip](https://github.com/m4heshd/whatsapp-desktop-dark/files/4394259/0.4.2080-Workaround.zip)
> **Windows**: WADark-Windows > styles > win32
> **macOS**: WADark-macOS > styles > darwin
> 
> Apply using the "default" theme on the GUI installer.

Thanks! Done!

**Comment by lowlabs** [comment]
Applied defaut theme with index.html from workaround, but there's a greenish tint. Looking at the colors in the default theme I don't think it's supposed to be this way... or is it?

<img width="766" alt="Screenshot 2020-04-19 at 19 11 04" src="https://user-images.githubusercontent.com/60349934/79694589-8efbbf80-8271-11ea-866c-31dd5709c552.png">

**Comment by facosta0787** [comment]
IS there any option to use other color schema with this workaround ?

**Comment by parresoft9** [comment]
apply and working, well done

**Comment by UnderEu** [comment]
> IS there any option to use other color schema with this workaround ?

No

**Comment by olucasmac** [comment]
> **WORKAROUND**: The following attachment enables the official dark theme as a temporary replacement. Replace the index.html files on the following path with the provided one:
> 
> [0.4.2080-Workaround.zip](https://github.com/m4heshd/whatsapp-desktop-dark/files/4394259/0.4.2080-Workaround.zip)
> **Windows**: WADark-Windows > styles > win32
> **macOS**: WADark-macOS > styles > darwin
> 
> Apply using the "default" theme on the GUI installer.


Works here! Thanks! ;)
WA 0.4.2088 | MacOS Catalina

**Comment by jontzi** [comment]
working! thanks! WA 0.4.2088 | Win 10

**Comment by roi007leaf** [comment]
> 
> 
> > IS there any option to use other color schema with this workaround ?
> 
> No

WhatsApp Dark works with this as well

**Comment by piraterex** [comment]
[see here](https://github.com/piraterex/WhatsApp-Desktop-Dark-Mode-Enabler)...now its easier than ever

**Comment by UnderEu** [comment]
> [see here](https://github.com/piraterex/WhatsApp-Desktop-Dark-Mode-Enabler)...now its easier than ever

Essentially, it's the same thing this tool does, except for the additional themes.
If people are interested in the official dark theme and only it, feel free to use it.

**Comment by ThexXTURBOXx** [comment]
Workaround works pretty well on Windows 10, 0.4.2088, except:
![image](https://user-images.githubusercontent.com/12763829/80368087-76506280-888c-11ea-80a5-231bc28815b7.png)
When you double click a text message, it will stay in a unreadable color (even when the respond message is already sent).

Edit: Seems to be fixed in WhatsApp release 2.2017.6 on WIndows. The workaround had nothing to do with it.

**Comment by sayanlp99** [comment]
> **WORKAROUND**: The following attachment enables the official dark theme as a temporary replacement. Replace the index.html files on the following path with the provided one:
> 
> [0.4.2080-Workaround.zip](https://github.com/m4heshd/whatsapp-desktop-dark/files/4394259/0.4.2080-Workaround.zip)
> **Windows**: WADark-Windows > styles > win32
> **macOS**: WADark-macOS > styles > darwin
> 
> Apply using the "default" theme on the GUI installer.

Worked for me on Windows 10

**Comment by crcoronado** [comment]
For me is working in Windows 10 and WP version 2.2017.6.

Please remember not only to replace the index.html file but also reinstall by running WADark.exe as Administrator.

**Comment by eyadsibai** [comment]
why don't you make a new release ?

**Comment by OliverGronowski** [comment]
Hi, there, it works but the start-up screen with the "loading circle" is the standard one (white background, green "loading circle") is still the same after changing from Default theme to Deep Black theme with this workaround for the first time.
I would apreciate it very much if you could fix that so it fits the applied theme.
![image](https://user-images.githubusercontent.com/45373843/81971071-ca936a80-9620-11ea-9e1d-bd77ae278b77.png)

**Comment by Koolstr** [comment]
Workaround actually works, thanks.

Is this project dead now, or are you working on it and we can expect an update eventually? If it's dead, that would be a real shame since I absolutely love this project and find it practically essential. At the very least, could we get a (final) release with this workaround built in as an option?

**Comment by devilishlyn** [comment]
> 
> 
> **WORKAROUND**: The following attachment enables the official dark theme as a temporary replacement. Replace the index.html files on the following path with the provided one:
> 
> [0.4.2080-Workaround.zip](https://github.com/m4heshd/whatsapp-desktop-dark/files/4394259/0.4.2080-Workaround.zip)
> **Windows**: WADark-Windows > styles > win32
> **macOS**: WADark-macOS > styles > darwin
> 
> Apply using the "default" theme on the GUI installer.

Thank you very much for this workaround! 
It works great man!

**Comment by olegnaopmaco** [comment]
> **WORKAROUND**: The following attachment enables the official dark theme as a temporary replacement. Replace the index.html files on the following path with the provided one:
> 
> [0.4.2080-Workaround.zip](https://github.com/m4heshd/whatsapp-desktop-dark/files/4394259/0.4.2080-Workaround.zip)
> **Windows**: WADark-Windows > styles > win32
> **macOS**: WADark-macOS > styles > darwin
> 
> Apply using the "default" theme on the GUI installer.

this works like a charm. Thank you

**Comment by swrobel** [comment]
@UnderEu why not just release a new version instead of directing everyone to this workaround?

**Comment by roceb** [comment]
Because the workaround isn't a release. It's simply changing one tag in the
HTML file.

**Comment by Th3Ph4nt0m** [comment]
@stopmyego than publish it as hotfix. But the latest version should already include that change because not every user is watching the issues.

**Comment by UnderEu** [comment]
> @UnderEu why not just release a new version instead of directing everyone to this workaround?

I am not the developer, just a contributorfor the project itself.

**Comment by eyadsibai** [comment]
you still can make a PR and merge it!

**Comment by ghost** [comment]
The funny thing is, to enable this hotfix to work, Whatsapp Desktop needs to be open... sadly, with the broken version, the normal app itself no longer even opens, regardless of changing the files, or opening as Admin etc.
A reinstall of the original Whatsapp Desktop is needed, for anyone still having this issue.


EDIT: nvm, it defaults to the normal Whatsapp theme after restarting PC. 😞

**Comment by joaoavilars** [comment]
Just a tip, upgraded to version 2.2021.4, tried to run the installer with the workaround to restore dark mode and it didn't work:
- download the latest version of Whatsapp directly from the Whatsapp website, reinstall and then apply the dark mode again with the workaround.
It worked that way for me on Windows.
![image](https://user-images.githubusercontent.com/42388872/84028323-e0b5f180-a966-11ea-8851-19ef6486d2aa.png)

**Comment by ghost** [comment]
> Just a tip, upgraded to version 2.2021.4, tried to run the installer with the workaround to restore dark mode and it didn't work:
> 
> * download the latest version of Whatsapp directly from the Whatsapp website, reinstall and then apply the dark mode again with the workaround.
>   It worked that way for me on Windows.

Exactly what I did, but every time I restart the machine it goes back to the original theme 😔

**Comment by Pitu** [comment]
Another temporary solution is the following:
- Modify your WhatsApp shortcut so it looks like the following `...\WhatsApp.exe --remote-debugging-port=8888` (Or any other port you want)
- Launch WhatsApp
- Go to `localhost:8888` (Or the port you wrote down)
- Add the class `dark` to the body
![image](https://user-images.githubusercontent.com/7425261/84049951-09ca9680-a9e8-11ea-802f-8e1c3c5a387d.png)

Adding the `--remote-debugging-port=8888` to the shortcut should be persistent across updates, so in the end the only thing you have to do once per day (or everytime you launch WhatsApp) is to navigate to your localhost and append the class once.

**Comment by ferkrodriguez98** [comment]
Tried building the script myself and applying this workaround but it stopped working, also, one of the packages has problems (resourcehacker), don't know if maybe that's a major issue.

**Comment by mechanizzed** [comment]
Stopped working on WhatsApp - 2.2023.2
MacOS

**Comment by jeromefaria** [comment]
This is what I do on macOS when it stops working. Please note that I install it through `brew cask` and I have the patched workaround downloaded to my `~/Downloads`.

```bash
brew cask reinstall whatsapp && ~/Downloads/WADark-macOS/WADark
```

This will reinstall WhatsApp and automatically open the page to apply the patch. After doing so, macOS usually throws me a warning that the binary file needs to be moved to the trash. Ignore that and run:

```bash
sudo xattr -rd com.apple.quarantine /Applications/WhatsApp.app
```

This is what works for me and continues to work with the latest version. Hope this helps!

**Comment by kriznik** [comment]
> Stopped working on WhatsApp - 2.2023.2
> MacOS

not working on 2.2023.2 on Windows as well

**Comment by SixSiege** [comment]
> > Stopped working on WhatsApp - 2.2023.2
> > MacOS
> 
> not working on 2.2023.2 on Windows as well

Same here

**Comment by ferkrodriguez98** [comment]
> This is what I do on macOS when it stops working. Please note that I install it through `brew cask` and I have the patched workaround downloaded to my `~/Downloads`.
> 
> ```shell
> brew cask reinstall whatsapp && ~/Downloads/WADark-macOS/WADark
> ```
> 
> This will reinstall WhatsApp and automatically open the page to apply the patch. After doing so, macOS usually throws me a warning that the binary file needs to be moved to the trash. Ignore that and run:
> 
> ```shell
> sudo xattr -rd com.apple.quarantine /Applications/WhatsApp.app
> ```
> 
> This is what works for me and continues to work with the latest version. Hope this helps!

@jeromefaria I'm doing exactly that but with no success. Wondering what could it be.

**Comment by UnderEu** [comment]
For those who clients updated to 2.2021.4 and 2.2023.2 (which the previous workaround stopped working), there's a fork by @firefinchdev with the official dark theme and settings enabled.
While @m4heshd is unable to update this one and all the built-in themes, that's the best we have for the moment.

Link: https://github.com/firefinchdev/whatsapp-desktop-dark

**Comment by ferkrodriguez98** [comment]
@firefinchdev 's fork works like a charm so far. Thanks @UnderEu !

**Comment by jeromefaria** [comment]
> For those who clients updated to 2.2021.4 and 2.2023.2 (which the previous workaround stopped working), there's a fork by @firefinchdev with the official dark theme and settings enabled.
> While @m4heshd is unable to update this one and all the built-in themes, that's the best we have for the moment.
> 
> Link: https://github.com/firefinchdev/whatsapp-desktop-dark

After a few attempts, this fork did not work on my system running 2.2023.2 on macOS.

**Comment by firefinchdev** [comment]
> > For those who clients updated to 2.2021.4 and 2.2023.2 (which the previous workaround stopped working), there's a fork by @firefinchdev with the official dark theme and settings enabled.
> > While @m4heshd is unable to update this one and all the built-in themes, that's the best we have for the moment.
> > Link: https://github.com/firefinchdev/whatsapp-desktop-dark
> 
> After a few attempts, this fork did not work on my system running 2.2023.2 on macOS.

You need to enable Dark mode by going in WA desktop settings -> Chats -> Theme

**Comment by jeromefaria** [comment]
> > After a few attempts, this fork did not work on my system running 2.2023.2 on macOS.
> 
> You need to enable Dark mode by going in WA desktop settings -> Chats -> Theme

Got it! Thank you @firefinchdev! 🙏🏻

**Comment by jeromefaria** [comment]
On 14/06/20 08:59, Anirudh Gupta wrote:
> > After a few attempts, this fork did not work on my system running 2.2023.2 on macOS.
> 
> You need to enable Dark mode by going in WA desktop settings -> Chats -> Theme
Got it! Thanks @firefinchdev! 🙏🏻

**Comment by jeromefaria** [comment]
> > After a few attempts, this fork did not work on my system running 2.2023.2 on macOS.
> 
> You need to enable Dark mode by going in WA desktop settings -> Chats -> Theme

Got it! Thanks @firefinchdev! 🙏🏻

**Comment by jeromefaria** [comment]
> > After a few attempts, this fork did not work on my system running 2.2023.2 on macOS.
> 
> You need to enable Dark mode by going in WA desktop settings -> Chats -> Theme

Got it! Thanks, @firefinchdev! 🙏🏻

By the way, any idea why I would get the following error while trying to install dependencies on your fork?

```bash
> resourcehacker@4.2.51 postinstall /Users/jeromefaria/Work/github/whatsapp-desktop-dark/node_modules/resourcehacker
> node scripts/install.js

Downloading ResourceHacker by Angus Johnson...
_http_client.js:108
  var expectedProtocol = defaultAgent.protocol;
                                      ^

TypeError: Cannot read property 'protocol' of undefined
    at new ClientRequest (_http_client.js:108:39)
    at request (http.js:42:10)
    at Object.get (http.js:46:13)
    at Object.<anonymous> (/Users/jeromefaria/Work/github/whatsapp-desktop-dark/node_modules/resourcehacker/scripts/install.js:23:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! resourcehacker@4.2.51 postinstall: `node scripts/install.js`
npm ERR! Exit status 1
```

**Comment by firefinchdev** [comment]
@jeromefaria See this https://github.com/m4heshd/whatsapp-desktop-dark/issues/25
