### ISSUE TITLE
EACCES: permission denied, unlink

### ISSUE THREAD

**Issue by BrUn3y** [m4heshd/whatsapp-desktop-dark#203]
Hello people
I have a problem with the installation in Mac OS and show me a message that the themes were successfully applied, but no

```sh
~~~~ WhatsApp Desktop Dark Mode by m4heshd ~~~~


WADark GUI installer backend started
WADark installer client connected. ID - nuyVJm4-aoAkW8z0AAAA

'/Applications/WhatsApp.app/Contents/Resources/app.asar'
    at Object.unlinkSync (fs.js:1018:3)
    at mayCopyFile (/Users/brun3y/Desktop/WADark-macOS/node_modules/fs-extra/lib/copy-sync/copy-sync.js:59:8)
    at onFile (/Users/brun3y/Desktop/WADark-macOS/node_modules/fs-extra/lib/copy-sync/copy-sync.js:54:10)
    at getStats (/Users/brun3y/Desktop/WADark-macOS/node_modules/fs-extra/lib/copy-sync/copy-sync.js:48:44)
    at startCopy (/Users/brun3y/Desktop/WADark-macOS/node_modules/fs-extra/lib/copy-sync/copy-sync.js:38:10)
    at handleFilterAndCopy (/Users/brun3y/Desktop/WADark-macOS/node_modules/fs-extra/lib/copy-sync/copy-sync.js:33:10)
    at Object.copySync (/Users/brun3y/Desktop/WADark-macOS/node_modules/fs-extra/lib/copy-sync/copy-sync.js:26:10)
    at /Users/brun3y/Desktop/WADark-macOS/run-gui.js:227:28
    at /Users/brun3y/Desktop/WADark-macOS/node_modules/asar/lib/asar.js:162:18
    at writeFileListToStream (/Users/brun3y/Desktop/WADark-macOS/node_modules/asar/lib/disk.js:42:10) {
  errno: -13,
  syscall: 'unlink',
  code: 'EACCES',
  path: '/Applications/WhatsApp.app/Contents/Resources/app.asar'
}

```

I hope that you can help me

**Comment by maxlfb** [comment]
Hey, you should try to `sudo` the command ;)

**Comment by WesleyNL** [comment]
I have the same issue
Windows

**Comment by BrUn3y** [comment]
:o works, than you
