### ISSUE TITLE
Windows - Install problem  errno: -4048  Error: EPERM: operation not permitted, unlink 

### ISSUE THREAD

**Issue by WesleyNL** [m4heshd/whatsapp-desktop-dark#208]
WADark GUI installer backend started
WADark installer client connected. ID - Z3KrJCUdUvUK1eD-AAAA

Theme "Default" was successfully applied.

TIP: You can create/download custom themes using "override.json" (Instructions are in the documentation)

Error: EPERM: operation not permitted, unlink 'C:\Program Files\WindowsApps\5319275A.WhatsAppDesktop_0.4.2089.0_x64__cv1g1gvanyjgm\app\resources\app.asar'
    at Object.unlinkSync (fs.js:1018:3)
    at mayCopyFile (E:\wesle\Downloads\WADark-0.4.930-Windows\WADark-Windows\node_modules\fs-extra\lib\copy-sync\copy-sync.js:59:8)
    at onFile (E:\wesle\Downloads\WADark-0.4.930-Windows\WADark-Windows\node_modules\fs-extra\lib\copy-sync\copy-sync.js:54:10)
    at getStats (E:\wesle\Downloads\WADark-0.4.930-Windows\WADark-Windows\node_modules\fs-extra\lib\copy-sync\copy-sync.js:48:44)
    at startCopy (E:\wesle\Downloads\WADark-0.4.930-Windows\WADark-Windows\node_modules\fs-extra\lib\copy-sync\copy-sync.js:38:10)
    at handleFilterAndCopy (E:\wesle\Downloads\WADark-0.4.930-Windows\WADark-Windows\node_modules\fs-extra\lib\copy-sync\copy-sync.js:33:10)
    at Object.copySync (E:\wesle\Downloads\WADark-0.4.930-Windows\WADark-Windows\node_modules\fs-extra\lib\copy-sync\copy-sync.js:26:10)
    at E:\wesle\Downloads\WADark-0.4.930-Windows\WADark-Windows\run-gui.js:227:28
    at E:\wesle\Downloads\WADark-0.4.930-Windows\WADark-Windows\node_modules\asar\lib\asar.js:162:18
    at writeFileListToStream (E:\wesle\Downloads\WADark-0.4.930-Windows\WADark-Windows\node_modules\asar\lib\disk.js:42:10) {
  errno: -4048,
  syscall: 'unlink',
  code: 'EPERM',
  path: 'C:\\Program Files\\WindowsApps\\5319275A.WhatsAppDesktop_0.4.2089.0_x64__cv1g1gvanyjgm\\app\\resources\\app.asar'
}

**Comment by ghost** [comment]
Same problem here

**Comment by m4heshd** [comment]
This is because you tried to install the dark mode on the store installed version of WhatsApp which is clearly mentioned in the documentation not to do. Try the direct downloaded version. Closing this.
