### ISSUE TITLE
EACCES: permission denied 

### ISSUE THREAD

**Issue by mrillusi0n** [m4heshd/whatsapp-desktop-dark#21]
Error: EACCES: permission denied, unlink '/Applications/WhatsApp.app/Contents/Resources/app.asar'
    at Object.unlinkSync (fs.js:976:3)
    at mayCopyFile (/Volumes/misc/WADark-mac/node_modules/fs-extra/lib/copy-sync/copy-sync.js:59:8)
    at onFile (/Volumes/misc/WADark-mac/node_modules/fs-extra/lib/copy-sync/copy-sync.js:54:10)
    at getStats (/Volumes/misc/WADark-mac/node_modules/fs-extra/lib/copy-sync/copy-sync.js:48:44)
    at startCopy (/Volumes/misc/WADark-mac/node_modules/fs-extra/lib/copy-sync/copy-sync.js:38:10)
    at handleFilterAndCopy (/Volumes/misc/WADark-mac/node_modules/fs-extra/lib/copy-sync/copy-sync.js:33:10)
    at Object.copySync (/Volumes/misc/WADark-mac/node_modules/fs-extra/lib/copy-sync/copy-sync.js:26:10)
    at /Volumes/misc/WADark-mac/run-darwin.js:100:28
    at /Volumes/misc/WADark-mac/node_modules/asar/lib/asar.js:162:18
    at writeFileListToStream (/Volumes/misc/WADark-mac/node_modules/asar/lib/disk.js:42:10) {
  errno: -13,
  syscall: 'unlink',
  code: 'EACCES',
  path: '/Applications/WhatsApp.app/Contents/Resources/app.asar'
}

**Comment by mrillusi0n** [comment]
When I use sudo, it was not able to find the WhatsApp process, although I had it open.

**Comment by m4heshd** [comment]
Hi @mrillusi0n,
This looks like a duplicate of https://github.com/m4heshd/whatsapp-desktop-dark/issues/3#issuecomment-527350198. Can you try to the solution mentioned in https://github.com/m4heshd/whatsapp-desktop-dark/issues/16? And make sure to run the script with `sudo` after you do the edits.

**Comment by mrillusi0n** [comment]
Solved. Thanks!

**Comment by m4heshd** [comment]
Good to hear. But It'll be great if you can explain how you managed to solve the issue.

**Comment by mrillusi0n** [comment]
I had downloaded it from the App Store. As on the other thread, I downloaded the file from WhatsApp's official site, it worked.
