### ISSUE TITLE
MacOS Mojave installation issue on V0.4.930 & V0.4.315

### ISSUE THREAD

**Issue by noslav** [m4heshd/whatsapp-desktop-dark#213]
```
> resourcehacker@4.2.51 /whatsapp-desktop-dark/node_modules/resourcehacker
> node scripts/install.js

Downloading ResourceHacker by Angus Johnson...
_http_client.js:139
  let expectedProtocol = defaultAgent.protocol;
                                      ^

TypeError: Cannot read property 'protocol' of undefined
    at new ClientRequest (_http_client.js:139:39)
    at request (http.js:46:10)
    at Object.get (http.js:50:15)
    at Object.<anonymous> (/Users/pranay/Downloads/Applications-upvest/WADark-macOS 2/whatsapp-desktop-dark/node_modules/resourcehacker/scripts/install.js:23:20)
    at Module._compile (internal/modules/cjs/loader.js:1128:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:983:32)
    at Function.Module._load (internal/modules/cjs/loader.js:891:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! resourcehacker@4.2.51 postinstall: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the resourcehacker@4.2.51 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pranay/.npm/_logs/2020-05-01T18_23_30_391Z-debug.log
```

I faced some issues with `npm install`. 
Otherwise works through the CLI installer.
Nice works guys!

**Comment by lucaashoff** [comment]
same here bro, the project is probably gonna end cause whastapp will release an official dark mode for desktop
