### ISSUE TITLE
v0.4.930 in w10 whats v2.2023.2 - not working anymore

### ISSUE THREAD

**Issue by ascrs** [m4heshd/whatsapp-desktop-dark#253]
After updating the app on w10, it was dark mode. I tried to reinstall and then it became a worse mess. Too bad ...
![whatsappweb](https://user-images.githubusercontent.com/19193416/84515135-72449c80-aca2-11ea-8a5d-769c6529892c.png)

**Comment by octvs** [comment]
Same here w/ macOS

**Comment by vdeniet** [comment]
> Same here w/ macOS

Here also

**Comment by firefinchdev** [comment]
I made a fork which is working. 
https://github.com/firefinchdev/whatsapp-desktop-dark
You can use it until it is merged in this repo.

**Comment by TheJokerArtZ** [comment]
> I made a fork which is working.
> https://github.com/firefinchdev/whatsapp-desktop-dark
> You can use it until it is merged in this repo.

your fix does not work for me

**Comment by octvs** [comment]
> I made a fork which is working.
> https://github.com/firefinchdev/whatsapp-desktop-dark
> You can use it until it is merged in this repo.

It worked for me on macOS Catalina

**Comment by captaindooley** [comment]
Thank you, this fix worked for me.

**Comment by rogeriskira** [comment]
> 
> 
> > I made a fork which is working.
> > https://github.com/firefinchdev/whatsapp-desktop-dark
> > You can use it until it is merged in this repo.
> 
> your fix does not work for me

It worked for me as well. Did you follow his instructions after it was installed? Go to Settings>Chats>Theme> Choose "Dark"

**Comment by guitexa** [comment]
It worked well for me, since I've go to Settings > Chats > Theme > Choose "Dark"

Thanks @firefinchdev 🙏

![whatsdark](https://user-images.githubusercontent.com/34251231/84784308-8a792c00-afc0-11ea-884d-82dcee49f9d3.jpg)

**Comment by JVDL-1** [comment]
Thanks this worked!

**Comment by 1800Kon** [comment]
> I made a fork which is working.
> https://github.com/firefinchdev/whatsapp-desktop-dark
> You can use it until it is merged in this repo.

This fix works perfectly!

**Comment by candestep** [comment]
> It worked well for me, since I've go to Settings > Chats > Theme > Choose "Dark"
> 
> Thanks @firefinchdev 🙏
> 
> ![whatsdark](https://user-images.githubusercontent.com/34251231/84784308-8a792c00-afc0-11ea-884d-82dcee49f9d3.jpg)

Where is this "Choose Dark" option? I'm using W10, but I can't find it anywhere in the Whatsapp application.

**Comment by 1800Kon** [comment]
@candestep click the 3 dots on the top left and then settings > theme > dark
![image](https://user-images.githubusercontent.com/55129891/85927575-5ac30180-b8a7-11ea-85b6-9fee8aedcea9.png)
D

![image](https://user-images.githubusercontent.com/55129891/85927577-61ea0f80-b8a7-11ea-8d06-8fd75f9b7460.png)

**Comment by candestep** [comment]
@KBG360 is that only available after installing the version by firefinchdev? https://github.com/firefinchdev/whatsapp-desktop-dark

My application does show the Theme option. I'm using Whatsapp 2.2025.7 by the way, and it is not the Microsoft Store version.

**Comment by firefinchdev** [comment]
@candestep Yes

**Comment by candestep** [comment]
@firefinchdev could you please help me? I'm new using Git, and I'm getting the following error when trying to install your package:

14012 verbose stack Error: resourcehacker@4.2.51 postinstall: `node scripts/install.js`
14012 verbose stack Exit status 1
14012 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
14012 verbose stack     at EventEmitter.emit (events.js:315:20)
14012 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
14012 verbose stack     at ChildProcess.emit (events.js:315:20)
14012 verbose stack     at maybeClose (internal/child_process.js:1021:16)
14012 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14013 verbose pkgid resourcehacker@4.2.51
14014 verbose cwd C:\Users\Israel Candelario\projects\whatsapp-desktop-dark
14015 verbose Windows_NT 10.0.18363
14016 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
14017 verbose node v12.18.1
14018 verbose npm  v6.14.5
14019 error code ELIFECYCLE
14020 error errno 1
14021 error resourcehacker@4.2.51 postinstall: `node scripts/install.js`
14021 error Exit status 1
14022 error Failed at the resourcehacker@4.2.51 postinstall script.
14022 error This is probably not a problem with npm. There is likely additional logging output above.
14023 verbose exit [ 1, true ]

Attached the error in the logs if that's helpful:
[2020-06-27T22_39_47_040Z-debug.log](https://github.com/m4heshd/whatsapp-desktop-dark/files/4841372/2020-06-27T22_39_47_040Z-debug.log)

**Comment by firefinchdev** [comment]
Open package.json and remove resource hacker

**Comment by candestep** [comment]
> Open package.json and remove resource hacker

Removed the whole _devDependecies_ object inside **package.json** that contained the work "_resourcehacker_". Installation progressed a little more but failed. This is what I got:


C:\Users\Israel Candelario\projects\whatsapp-desktop-dark>npm install
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated

> resourcehacker@4.2.51 postinstall C:\Users\Israel Candelario\projects\whatsapp-desktop-dark\node_modules\resourcehacker
> node scripts/install.js

Downloading ResourceHacker by Angus Johnson...
_http_client.js:140
  let expectedProtocol = defaultAgent.protocol;
                                      ^

TypeError: Cannot read property 'protocol' of undefined
    at new ClientRequest (_http_client.js:140:39)
    at request (http.js:46:10)
    at Object.get (http.js:50:15)
    at Object.<anonymous> (C:\Users\Israel Candelario\projects\whatsapp-desktop-dark\node_modules\resourcehacker\scripts\install.js:23:20)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! resourcehacker@4.2.51 postinstall: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the resourcehacker@4.2.51 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Israel Candelario\AppData\Roaming\npm-cache\_logs\2020-06-27T23_25_29_285Z-debug.log

**Comment by firefinchdev** [comment]
You only need to remove resource hacker, not entire devDependencies. By the way, if you are not comfortable with all this manual build, pre build binaries are available. Just go though the Readme of the fork.

**Comment by candestep** [comment]
... thank you.

Used the prebuild and worked like a charm. Not sure why I thought I needed to go through the manual process, good learning experience anyway.

Thank you so much for your help!
