### ISSUE TITLE
Error in installation | "Error: ENOENT: no such file or directory"

### ISSUE THREAD

**Issue by lindeberg** [m4heshd/whatsapp-desktop-dark#45]
![image](https://user-images.githubusercontent.com/15940340/66041750-e8d9a980-e51a-11e9-9d23-cbbe26fae324.png)

`Backing up..
{ Error: ENOENT: no such file or directory, stat 'C:\Users\M�lle\AppData\Local\WhatsApp\app-0.3.4679\resources\app.asar'
    at Object.fs.statSync (fs.js:948:11)
    at Object.statSync (C:\Users\Mölle\Downloads\whatsapp-desktop-dark-master\whatsapp-desktop-dark-master\node_modules\graceful-fs\polyfills.js:308:16)
    at getStatsSync (C:\Users\Mölle\Downloads\whatsapp-desktop-dark-master\whatsapp-desktop-dark-master\node_modules\fs-extra\lib\util\stat.js:60:18)
    at Object.checkPathsSync (C:\Users\Mölle\Downloads\whatsapp-desktop-dark-master\whatsapp-desktop-dark-master\node_modules\fs-extra\lib\util\stat.js:90:33)
    at Object.copySync (C:\Users\Mölle\Downloads\whatsapp-desktop-dark-master\whatsapp-desktop-dark-master\node_modules\fs-extra\lib\copy-sync\copy-sync.js:24:38)
    at applyDarkStyles (C:\Users\Mölle\Downloads\whatsapp-desktop-dark-master\whatsapp-desktop-dark-master\run-win32.js:87:12)
    at C:\Users\Mölle\Downloads\whatsapp-desktop-dark-master\whatsapp-desktop-dark-master\run-win32.js:54:29
    at C:\Users\Mölle\Downloads\whatsapp-desktop-dark-master\whatsapp-desktop-dark-master\run-win32.js:233:17
    at Interface._onLine (readline.js:278:5)
    at Interface._line (readline.js:629:8)
  errno: -4058,
  code: 'ENOENT',
  syscall: 'stat',
  path: 'C:\\Users\\M�lle\\AppData\\Local\\WhatsApp\\app-0.3.4679\\resources\\app.asar' }`

My guess is it is because I have scandinavian letters in my windows user name "Mölle"?

**Comment by m4heshd** [comment]
You guessed right and this is a duplicate of issue #29. You can find the solution there.

**Comment by lindeberg** [comment]
Ah. Thanks! So appreciate this project.

**Comment by m4heshd** [comment]
It's my pleasure.. 🙂
