### ISSUE TITLE
Dark theme killed by new Windows Update

### ISSUE THREAD

**Issue by lacfantome** [m4heshd/whatsapp-desktop-dark#76]
Hi, 
the dark theme is no longer working since the last Windows 10 update, even when I try to reinstall it

**Comment by RuggeDX** [comment]
Does the installer not report any issues during the installation?

**Comment by virtuaspectro** [comment]
I'm getting the same error while installing directly from the command line.

The current version of Whatsapp Web (Win10) is 0.3.5148. Maybe they have changed that defaultAgent object.

This is the error output after npm install:
```
Downloading ResourceHacker by Angus Johnson...
_http_client.js:107
  var expectedProtocol = defaultAgent.protocol;
                                      ^

TypeError: Cannot read property 'protocol' of undefined
    at new ClientRequest (_http_client.js:107:39)
    at request (http.js:42:10)
    at Object.get (http.js:46:13)
    at Object.<anonymous> (C:\Users\spectro\whatsapp-desktop-dark\node_modules\resourcehacker\scripts\install.js:23:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
```

**Comment by m4heshd** [comment]
Closing this since everything is fixed in the latest release.
