### ISSUE TITLE
Mac OS: error -13

### ISSUE THREAD

**Issue by aeonoea** [m4heshd/whatsapp-desktop-dark#99]
I've tried to install on a Macbook Air on latest OS (no beta) and WA version without success. I have followed the steps from https://github.com/m4heshd/whatsapp-desktop-dark/issues/91#issuecomment-550118936 multiple times and rebooted twice and it always resulted in the following error:

> Backing up..
Extracting..
Injecting styles..
Replacing files..
Error: EACCES: permission denied, unlink '/Applications/WhatsApp.app/Contents/Resources/app.asar'
    at Object.unlinkSync (fs.js:1018:3)
    at mayCopyFile (/Users/xxx/Downloads/WADark-mac/node_modules/fs-extra/lib/copy-sync/copy-sync.js:59:8)
    at onFile (/Users/xxx/Downloads/WADark-mac/node_modules/fs-extra/lib/copy-sync/copy-sync.js:54:10)
    at getStats (/Users/xxx/Downloads/WADark-mac/node_modules/fs-extra/lib/copy-sync/copy-sync.js:48:44)
    at startCopy (/Users/xxx/Downloads/WADark-mac/node_modules/fs-extra/lib/copy-sync/copy-sync.js:38:10)
    at handleFilterAndCopy (/Users/xxx/Downloads/WADark-mac/node_modules/fs-extra/lib/copy-sync/copy-sync.js:33:10)
    at Object.copySync (/Users/xxx/Downloads/WADark-mac/node_modules/fs-extra/lib/copy-sync/copy-sync.js:26:10)
    at /Users/xxx/Downloads/WADark-mac/run-darwin.js:111:28
    at /Users/xxx/Downloads/WADark-mac/node_modules/asar/lib/asar.js:162:18
    at writeFileListToStream (/Users/xxx/Downloads/WADark-mac/node_modules/asar/lib/disk.js:42:10) {
  errno: -13,
  syscall: 'unlink',
  code: 'EACCES',
  path: '/Applications/WhatsApp.app/Contents/Resources/app.asar'
}
An error occurred. Cleaning up..

**Comment by mwilzin** [comment]
You've to run Script with sudo rights in the Terminal.
Just write "sudo" and than drag the file into the terminal and hit enter.

**Comment by aeonoea** [comment]
> You've to run Script with sudo rights in the Terminal.
> Just write "sudo" and than drag the file into the terminal and hit enter.

That solved it, thank you very much.

**Comment by m4heshd** [comment]
Closing this since the issue has been solved.
